# Harmonica — self-hosted image (Next.js standalone output).
#
# Debian slim rather than Alpine on purpose: the dependency tree contains native
# modules (tree-sitter, bufferutil) and llamaindex pulls in onnxruntime bindings,
# which are built against glibc. Alpine's musl libc turns those into build- and
# run-time surprises.

# ---------- deps ----------
FROM node:20-bookworm-slim AS deps
WORKDIR /app

# Toolchain for the native modules above; node-gyp needs python3/make/g++.
RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 make g++ ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# package-lock.json was generated by npm 11, which resolves optional peer
# dependencies differently from the npm 10 shipped with Node 20. Without this,
# `npm ci` aborts with "Missing: next@15.x from lock file" — @llamaindex/
# workflow-core declares an optional peer dependency on Next 15.
RUN npm install -g npm@11.17.0

COPY package.json package-lock.json ./
RUN npm ci

# ---------- builder ----------
FROM node:20-bookworm-slim AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# AUTH0_BASE_URL is inlined into the bundle at build time by next.config.js, so
# that Auth0 config is available inside the edge middleware. Changing the public
# URL therefore requires a rebuild, not just an env var change.
ARG AUTH0_BASE_URL
ENV AUTH0_BASE_URL=$AUTH0_BASE_URL

# next.config.js is evaluated during the build, so the server-action origin
# allowlist is baked into the output and has to be a build argument too.
ARG SERVER_ACTIONS_ALLOWED_ORIGINS
ENV SERVER_ACTIONS_ALLOWED_ORIGINS=$SERVER_ACTIONS_ALLOWED_ORIGINS

# AGPL-3.0 §13 requires offering the source of the *running* version, so the
# in-app link points at the commit this image was built from — a branch link
# would drift as soon as anything else is pushed. SOURCE_COMMIT lets a build
# platform supply it; otherwise it is read from the checkout below.
ARG SOURCE_COMMIT
ARG NEXT_PUBLIC_SOURCE_URL
ENV NEXT_PUBLIC_SOURCE_URL=$NEXT_PUBLIC_SOURCE_URL

# Build-time-only placeholders. `next build` evaluates module scope of every
# route, and two modules construct clients eagerly:
#   - src/lib/schema.ts reads POSTGRES_URL (a 'localhost' value selects the pg
#     driver, which connects lazily — so no database is needed to build)
#   - src/lib/stripe.ts and the Stripe webhook route call `new Stripe(key!)`,
#     which throws on an empty key
# Real values are supplied at runtime by the deployment environment.
ENV POSTGRES_URL=postgresql://build:build@localhost:5432/build \
    STRIPE_SECRET_KEY=sk_test_build_placeholder \
    SUMMARY_ASSISTANT= \
    NEXT_TELEMETRY_DISABLED=1

# The commit comes from the build platform when it provides one, and from the
# checkout itself otherwise, so the link is correct however the image is built.
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/* \
    && export NEXT_PUBLIC_SOURCE_COMMIT="${SOURCE_COMMIT:-$(git rev-parse HEAD 2>/dev/null || echo '')}" \
    && echo "building from commit: ${NEXT_PUBLIC_SOURCE_COMMIT:-unknown}" \
    && npm run build

# Compile the migrator and each migration to standalone CJS so the runtime image
# can migrate itself without carrying tsx and the full node_modules tree.
# Migrations stay separate files because Kysely's FileMigrationProvider reads the
# directory at runtime and imports each one; only their names identify them.
RUN npx esbuild src/db/migrator.ts \
      --bundle --platform=node --target=node20 --format=cjs \
      --external:pg-native \
      --outfile=dist-migrate/migrator.js \
    && npx esbuild src/db/migrations/*.ts \
      --bundle --platform=node --target=node20 --format=cjs \
      --external:pg-native \
      --outdir=dist-migrate/migrations

# ---------- runner ----------
FROM node:20-bookworm-slim AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN groupadd --system --gid 1001 nodejs \
    && useradd --system --uid 1001 --gid nodejs nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Message catalogs are bundled by the dynamic import in src/i18n/request.ts;
# copied as well so a locale added later does not silently 404.
COPY --from=builder --chown=nextjs:nodejs /app/messages ./messages
COPY --from=builder --chown=nextjs:nodejs /app/dist-migrate ./dist-migrate

COPY docker-entrypoint.sh /app/docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh

USER nextjs
EXPOSE 3000

CMD ["/app/docker-entrypoint.sh"]
